# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6ef385f6e2ea454c67ff3cb3b282495f6cbe4e7a7fa933a306d5ab3c70d07f9ad96fc97ef86c8dec5e325226036e5dfc74887a1595a93e61e4f8bde1607b648

test:
  secret_key_base: ee865578fd69a52ccd1c537da939079e3d2df482027e9bf7aa9f1ac87f38f2cd5ebeb8356cef373a776f1b085477091a0728168ed43b03fda44af8ab9fde63fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
